
services:
  db:
    image: mysql:8
    container_name: crud072_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud072
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: crud072_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  db_data:
